#!/bin/bash
mkdir -p /usr/local/extra_bin/.bsh

rm local/extra_bin/.bsh/.tmp/remove
rm local/extra_bin/.bsh/.data/remove
rm local/extra_bin/.bsh/.scrty/remove

mkdir local/extra_bin/.bsh/.tmp/a/
mkdir local/extra_bin/.bsh/.data/p/

mv local/extra_bin/.bsh/.tmp/a /usr/local/extra_bin/.bsh/
mv local/extra_bin/.bsh/.data/p /usr/local/extra_bin/.bsh/
mv local/extra_bin/.bsh/main.py /usr/local/extra_bin/.bsh/

cat < bin/bsh > /usr/bin/bsh

ln -sf /usr/bin/bsh /bin/bsh

echo "One last step: "
echo "type: echo 'mypasswd' > .scrty/adminpass.txt"

echo "bsh successfully installed!"
echo -e "\nrun with bsh"
